name: Team labeler

on: pull_request

jobs:
  team-labeler:
    uses: CoSchedule/platform/.github/workflows/team-labeler.yml@v1
    permissions:
      contents: read
      pull-requests: write
    with:
      app-client-id: ${{ vars.COSCHEDULE_APP_CLIENT_ID }}
    secrets:
      app-private-key: ${{ secrets.COSCHEDULE_APP_PRIVATE_KEY }}
